<a href="https://colab.research.google.com/github/yeyomuri/numpy/blob/main/colab/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Numpy

Numpy es una libreria que nos permite gestionar vectores, matrices.

A diferencia de las listas de Python, Numpy nos permite que nuestras listas sean staticas y no dinamicas. Esto va permitir optimizar nuestros arreglos ocupando menos espacio de memoria.

El implementacion de numpy es vectorizada, facilitando la redundancia de crear ciclos dando como resultado menos lineas de código y menos erres de escritura

La documentacion oficial esta en [Numpy](https://numpy.org/), y la guia rapida esta en [Guia Rapida](https://numpy.org/doc/stable/user/quickstart.html)


In [1]:
import numpy as np


In [15]:
#Creacion de un una matriz (2, 3)

[[3,3,5], [3, 2, 1]]

[[3, 3, 5], [3, 2, 1]]

In [37]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [20]:
a.shape

(3, 5)

In [25]:
a.dtype.name

'int64'

In [38]:
#Representa el tamaño en bytes del tipo de dato del arreglo int64 bit es equibalente a 8 ó (64/8)
a.itemsize 

8

In [40]:
a.size

15

In [42]:
  type(a)

numpy.ndarray

In [45]:
b = np.array([5,4,3])
b

array([5, 4, 3])

In [46]:
type(b)

numpy.ndarray

##Creación de array

In [50]:
a = np.array([2,3,4])
a.dtype

dtype('int64')

In [48]:
b = np.array([2.4, 3.2, 5.4])
b.dtype

dtype('float64')

In [52]:
#Arreglo secuencia de secuencia de secuencia
b = np.array([(3,2,1), (6,4,7)])
b

array([[3, 2, 1],
       [6, 4, 7]])

In [55]:
b = np.array([(3,4,6), (6,7,4)], dtype = complex)
b

array([[3.+0.j, 4.+0.j, 6.+0.j],
       [6.+0.j, 7.+0.j, 4.+0.j]])

In [59]:
#Creando una matriz de ceros
np.zeros((3,4), dtype = np.int8)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [67]:
#Arreglo de arreglo
a = np.ones((4, 3, 4), dtype = np.int16)
a

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [71]:
#Matriz de nulos 
np.empty((2, 3))


array([[1.39069238e-309, 1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309, 1.39069238e-309]])

In [81]:
#Generador de valores (arange)
np.arange(10, 100, 3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [80]:
#Generador distribuye numero de valores en un rango (linspace)
np.linspace(0, 2, 90)

array([0.        , 0.02247191, 0.04494382, 0.06741573, 0.08988764,
       0.11235955, 0.13483146, 0.15730337, 0.17977528, 0.20224719,
       0.2247191 , 0.24719101, 0.26966292, 0.29213483, 0.31460674,
       0.33707865, 0.35955056, 0.38202247, 0.40449438, 0.42696629,
       0.4494382 , 0.47191011, 0.49438202, 0.51685393, 0.53932584,
       0.56179775, 0.58426966, 0.60674157, 0.62921348, 0.65168539,
       0.6741573 , 0.69662921, 0.71910112, 0.74157303, 0.76404494,
       0.78651685, 0.80898876, 0.83146067, 0.85393258, 0.87640449,
       0.8988764 , 0.92134831, 0.94382022, 0.96629213, 0.98876404,
       1.01123596, 1.03370787, 1.05617978, 1.07865169, 1.1011236 ,
       1.12359551, 1.14606742, 1.16853933, 1.19101124, 1.21348315,
       1.23595506, 1.25842697, 1.28089888, 1.30337079, 1.3258427 ,
       1.34831461, 1.37078652, 1.39325843, 1.41573034, 1.43820225,
       1.46067416, 1.48314607, 1.50561798, 1.52808989, 1.5505618 ,
       1.57303371, 1.59550562, 1.61797753, 1.64044944, 1.66292

In [90]:
from numpy import pi
x = np.linspace(0, pi, 100)
f = np.sin(x)
f

array([0.00000000e+00, 3.17279335e-02, 6.34239197e-02, 9.50560433e-02,
       1.26592454e-01, 1.58001396e-01, 1.89251244e-01, 2.20310533e-01,
       2.51147987e-01, 2.81732557e-01, 3.12033446e-01, 3.42020143e-01,
       3.71662456e-01, 4.00930535e-01, 4.29794912e-01, 4.58226522e-01,
       4.86196736e-01, 5.13677392e-01, 5.40640817e-01, 5.67059864e-01,
       5.92907929e-01, 6.18158986e-01, 6.42787610e-01, 6.66769001e-01,
       6.90079011e-01, 7.12694171e-01, 7.34591709e-01, 7.55749574e-01,
       7.76146464e-01, 7.95761841e-01, 8.14575952e-01, 8.32569855e-01,
       8.49725430e-01, 8.66025404e-01, 8.81453363e-01, 8.95993774e-01,
       9.09631995e-01, 9.22354294e-01, 9.34147860e-01, 9.45000819e-01,
       9.54902241e-01, 9.63842159e-01, 9.71811568e-01, 9.78802446e-01,
       9.84807753e-01, 9.89821442e-01, 9.93838464e-01, 9.96854776e-01,
       9.98867339e-01, 9.99874128e-01, 9.99874128e-01, 9.98867339e-01,
       9.96854776e-01, 9.93838464e-01, 9.89821442e-01, 9.84807753e-01,
      

In [91]:
w = np.zeros_like(x)
w

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])