<a href="https://colab.research.google.com/github/yeyomuri/numpy/blob/main/numpy/colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Numpy

Numpy es una libreria que nos permite gestionar vectores, matrices.

A diferencia de las listas de Python, Numpy nos permite que nuestras listas sean staticas y no dinamicas. Esto va permitir optimizar nuestros arreglos ocupando menos espacio de memoria.

El implementacion de numpy es vectorizada, facilitando la redundancia de crear ciclos dando como resultado menos lineas de código y menos erres de escritura

La documentacion oficial esta en [Numpy](https://numpy.org/), y la guia rapida esta en [Guia Rapida](https://numpy.org/doc/stable/user/quickstart.html)


In [63]:
import numpy as np


In [64]:
#Creacion de un una matriz (2, 3)

[[3,3,5], [3, 2, 1]]

[[3, 3, 5], [3, 2, 1]]

In [65]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [66]:
a.shape

(3, 5)

In [67]:
a.dtype.name

'int64'

In [68]:
#Representa el tamaño en bytes del tipo de dato del arreglo int64 bit es equibalente a 8 ó (64/8)
a.itemsize 

8

In [69]:
a.size

15

In [70]:
  type(a)

numpy.ndarray

In [71]:
b = np.array([5,4,3])
b

array([5, 4, 3])

In [72]:
type(b)

numpy.ndarray

##Creación de array

In [73]:
a = np.array([2,3,4])
a.dtype

dtype('int64')

In [74]:
b = np.array([2.4, 3.2, 5.4])
b.dtype

dtype('float64')

In [75]:
#Arreglo secuencia de secuencia de secuencia
b = np.array([(3,2,1), (6,4,7)])
b

array([[3, 2, 1],
       [6, 4, 7]])

In [76]:
b = np.array([(3,4,6), (6,7,4)], dtype = complex)
b

array([[3.+0.j, 4.+0.j, 6.+0.j],
       [6.+0.j, 7.+0.j, 4.+0.j]])

In [77]:
#Creando una matriz de ceros
np.zeros((3,4), dtype = np.int8)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [78]:
#Arreglo de arreglo
a = np.ones((4, 3, 4), dtype = np.int16)
a

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [79]:
#Matriz de nulos 
np.empty((2, 3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [80]:
#Generador de valores (arange)
np.arange(10, 100, 3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [81]:
#Generador distribuye numero de valores en un rango (linspace)
np.linspace(0, 2, 90)

array([0.        , 0.02247191, 0.04494382, 0.06741573, 0.08988764,
       0.11235955, 0.13483146, 0.15730337, 0.17977528, 0.20224719,
       0.2247191 , 0.24719101, 0.26966292, 0.29213483, 0.31460674,
       0.33707865, 0.35955056, 0.38202247, 0.40449438, 0.42696629,
       0.4494382 , 0.47191011, 0.49438202, 0.51685393, 0.53932584,
       0.56179775, 0.58426966, 0.60674157, 0.62921348, 0.65168539,
       0.6741573 , 0.69662921, 0.71910112, 0.74157303, 0.76404494,
       0.78651685, 0.80898876, 0.83146067, 0.85393258, 0.87640449,
       0.8988764 , 0.92134831, 0.94382022, 0.96629213, 0.98876404,
       1.01123596, 1.03370787, 1.05617978, 1.07865169, 1.1011236 ,
       1.12359551, 1.14606742, 1.16853933, 1.19101124, 1.21348315,
       1.23595506, 1.25842697, 1.28089888, 1.30337079, 1.3258427 ,
       1.34831461, 1.37078652, 1.39325843, 1.41573034, 1.43820225,
       1.46067416, 1.48314607, 1.50561798, 1.52808989, 1.5505618 ,
       1.57303371, 1.59550562, 1.61797753, 1.64044944, 1.66292

In [82]:
from numpy import pi
x = np.linspace(0, pi, 100)
f = np.sin(x)
f

array([0.00000000e+00, 3.17279335e-02, 6.34239197e-02, 9.50560433e-02,
       1.26592454e-01, 1.58001396e-01, 1.89251244e-01, 2.20310533e-01,
       2.51147987e-01, 2.81732557e-01, 3.12033446e-01, 3.42020143e-01,
       3.71662456e-01, 4.00930535e-01, 4.29794912e-01, 4.58226522e-01,
       4.86196736e-01, 5.13677392e-01, 5.40640817e-01, 5.67059864e-01,
       5.92907929e-01, 6.18158986e-01, 6.42787610e-01, 6.66769001e-01,
       6.90079011e-01, 7.12694171e-01, 7.34591709e-01, 7.55749574e-01,
       7.76146464e-01, 7.95761841e-01, 8.14575952e-01, 8.32569855e-01,
       8.49725430e-01, 8.66025404e-01, 8.81453363e-01, 8.95993774e-01,
       9.09631995e-01, 9.22354294e-01, 9.34147860e-01, 9.45000819e-01,
       9.54902241e-01, 9.63842159e-01, 9.71811568e-01, 9.78802446e-01,
       9.84807753e-01, 9.89821442e-01, 9.93838464e-01, 9.96854776e-01,
       9.98867339e-01, 9.99874128e-01, 9.99874128e-01, 9.98867339e-01,
       9.96854776e-01, 9.93838464e-01, 9.89821442e-01, 9.84807753e-01,
      

In [83]:
w = np.zeros_like(x)
w

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Impremir arreglos

In [84]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [85]:
#Reshape permite transformar un vector en arreglo multimencional  
b = np.arange(12).reshape(4, 3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [86]:
c = np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


Operaciones basicas 

In [87]:
a = np.arange(4)
b = np.array([20,30,40,50])

c = a - b
print('El valor de C es: ', c)

d = b**2
print('El valor de D es: ', d)
w = np.sin(a)

print('El sin del arregle a es: ', w)

b < 23


El valor de C es:  [-20 -29 -38 -47]
El valor de D es:  [ 400  900 1600 2500]
El sin del arregle a es:  [0.         0.84147098 0.90929743 0.14112001]


array([ True, False, False, False])

In [88]:
A = np.array([[1,2], [2, 3]])
B = np.array([[3,5], [2, 4]])

#Product element wise
print('El producto element wise A * B es')
A * B

#Producto de matrices
print('El producto matricial es')
A @ B

#Producto punto de A . B es
print('El producto punto A . B es')
A.dot(B)


El producto element wise A * B es
El producto matricial es
El producto punto A . B es


array([[ 7, 13],
       [12, 22]])

In [89]:
rg = np.random.default_rng(1)
a = np.ones((2, 3), dtype = int)
b = rg.random((2,3))
a *= 3
a

b += a
b



array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [90]:
a = np.ones(3, dtype = int)
b = np.linspace(0, pi, 3)
b.dtype.name

c = a+b
print(c)
d = np.exp(c * 1j)
print(d)
d.dtype.name


[1.         2.57079633 4.14159265]
[ 0.54030231+0.84147098j -0.84147098+0.54030231j -0.54030231-0.84147098j]


'complex128'

In [91]:
#Operaciones unarias
rg2 = np.random.default_rng(1)
a = rg2.random((2,3))
print(a)
print('La suma de los elentos de la matrz A es: ', a.sum())
print('El valor minimo de la matrz A es: ', a.min())
print('El valor maximo de la matriz A es: ', a.max())


[[0.51182162 0.9504637  0.14415961]
 [0.94864945 0.31183145 0.42332645]]
La suma de los elentos de la matrz A es:  3.290252281866131
El valor minimo de la matrz A es:  0.14415961271963373
El valor maximo de la matriz A es:  0.9504636963259353


In [92]:
b = np.arange(12). reshape(3, 4)
print(b)
print('La suma de cada columna es: ', b.sum(axis = 0))
print('El valor minimo de b es: ', b.min(axis = 1))
print('La suma acomulativa de cada colomna es: \n', b.cumsum(axis = 1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
La suma de cada columna es:  [12 15 18 21]
El valor minimo de b es:  [0 4 8]
La suma acomulativa de cada colomna es: 
 [[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


Funciones universales

In [93]:
B = np.arange(3)
print('B: ', B)
print('La exponencial de cada uno de los valores de la matriz B es: ', np.exp(B))
print('La raiz cuadrada de cada uno de los valores de la metrz B es: ', np.sqrt(B))
C = np.array([3,2,5])
print('A mas B es: ', np.add(B, C))


B:  [0 1 2]
La exponencial de cada uno de los valores de la matriz B es:  [1.         2.71828183 7.3890561 ]
La raiz cuadrada de cada uno de los valores de la metrz B es:  [0.         1.         1.41421356]
A mas B es:  [3 3 7]


Las matrices unidemencionales se pueden dividir, indexar e iterar al igual que las listas de python

In [94]:
a = np.arange(10)**3
print('El valor de a al cubo es: ', a)
print('El valor de la tercera posicion de la matriz a es: ', a[2])
print('Un sub vector de a es', a[2: 5])
print('Añadir elementos en un subconjunto: ')
sub_add_a = a[:6:2] = 1000
print(sub_add_a)
print('El vector en sentido contrario es: ', a[::-1])
for i in a: 
  print(i**(1/3))
b[-1:]


El valor de a al cubo es:  [  0   1   8  27  64 125 216 343 512 729]
El valor de la tercera posicion de la matriz a es:  8
Un sub vector de a es [ 8 27 64]
Añadir elementos en un subconjunto: 
1000
El vector en sentido contrario es:  [ 729  512  343  216  125 1000   27 1000    1 1000]
9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


array([[ 8,  9, 10, 11]])

Manipulacion de formas

In [95]:
#Cambiando la forma de un array

a = np.floor(10 * rg.random((3, 4)))
print('El vector a es: \n', a)
print('Las dimensiones de la matriz a es: ', a.shape)
print('Devuelve el arreglo en una dimension: ', a.ravel())
print('Retorna el array con las dimensiones modificadas: ', a.reshape(6, 2))
print('Retorna la transpuesta de la matriz a: \n', a.T)
print('Las dimensione de la matriz transpuesta es: ', a.T.shape)
print('Redimensionando con resize es: ', a.resize((2, 6)))
print('La redimension automatica es: \n', a.reshape(3, -1))

El vector a es: 
 [[8. 4. 5. 0.]
 [7. 5. 3. 7.]
 [3. 4. 1. 4.]]
Las dimensiones de la matriz a es:  (3, 4)
Devuelve el arreglo en una dimension:  [8. 4. 5. 0. 7. 5. 3. 7. 3. 4. 1. 4.]
Retorna el array con las dimensiones modificadas:  [[8. 4.]
 [5. 0.]
 [7. 5.]
 [3. 7.]
 [3. 4.]
 [1. 4.]]
Retorna la transpuesta de la matriz a: 
 [[8. 7. 3.]
 [4. 5. 4.]
 [5. 3. 1.]
 [0. 7. 4.]]
Las dimensione de la matriz transpuesta es:  (4, 3)
Redimensionando con resize es:  None
La redimension automatica es: 
 [[8. 4. 5. 0.]
 [7. 5. 3. 7.]
 [3. 4. 1. 4.]]


In [96]:
a = np.floor(10*rg.random((2,2)))
print('La matriz a es: \n', a)
b = np.floor(10*rg.random((2,2)))
print('La matriz b es: \n')
print('La apilacion vertical de las matrices es: \n', np.vstack((a, b)))
print('La apilacion horizontal de las matrices es: \n', np.hstack((a, b)))

La matriz a es: 
 [[2. 2.]
 [7. 2.]]
La matriz b es: 

La apilacion vertical de las matrices es: 
 [[2. 2.]
 [7. 2.]
 [4. 9.]
 [9. 7.]]
La apilacion horizontal de las matrices es: 
 [[2. 2. 4. 9.]
 [7. 2. 9. 7.]]


In [97]:
from numpy import newaxis
print('apilacion horizontal para matriz 2x2: \n', np.column_stack((a, b)))

a = np.array([3,2.])
b = np.array([3, 5])

print('La apicacion con column stack es: \n', np.column_stack((a, b)))
print('La apilacion es diferente a column_stack: \n', np.hstack((a, b)))
print('La transposicion de a es: \n', a[:, newaxis])
print('la transposicion de a y b apilados es: \n', np.column_stack((a[:, newaxis], b[:, newaxis])))
print('La transposicion de a y b apilados con hstack es \n', np.hstack((a[:, newaxis], b[:, newaxis])))

apilacion horizontal para matriz 2x2: 
 [[2. 2. 4. 9.]
 [7. 2. 9. 7.]]
La apicacion con column stack es: 
 [[3. 3.]
 [2. 5.]]
La apilacion es diferente a column_stack: 
 [3. 2. 3. 5.]
La transposicion de a es: 
 [[3.]
 [2.]]
la transposicion de a y b apilados es: 
 [[3. 3.]
 [2. 5.]]
La transposicion de a y b apilados con hstack es 
 [[3. 3.]
 [2. 5.]]


División de una matriz en varias más pequeñas

In [98]:
a = np.floor(10*rg.random((2,12)))

print('La matriz a es: \n', a)
print('La division en 3 de la matriz a es: \n', np.hsplit(a, 3))
print('la division de la matriz en la columna #N es: ', np.hsplit(a, (3, 4)))

La matriz a es: 
 [[5. 2. 1. 9. 5. 1. 6. 7. 6. 9. 0. 5.]
 [4. 0. 6. 8. 5. 2. 8. 5. 5. 7. 1. 8.]]
La division en 3 de la matriz a es: 
 [array([[5., 2., 1., 9.],
       [4., 0., 6., 8.]]), array([[5., 1., 6., 7.],
       [5., 2., 8., 5.]]), array([[6., 9., 0., 5.],
       [5., 7., 1., 8.]])]
la division de la matriz en la columna #N es:  [array([[5., 2., 1.],
       [4., 0., 6.]]), array([[9.],
       [8.]]), array([[5., 1., 6., 7., 6., 9., 0., 5.],
       [5., 2., 8., 5., 5., 7., 1., 8.]])]


Copias y vistas


In [99]:
#Sin copia en absoluto
a = np.array([[0,1,2,3], [4,5,6,7], [8,9,10,11]])
#No se crea un nuevo objeto
b = a
print(b)
#Dos nombres diferentes apuntan a la misma direccion de memoria
a is b

#Python pasa los valores a las funciones como parametros mutables, por lo que la llamada no se copia
def f(x):
  print(id(x))

print('La direccion de memoria de a es: ', id(a))
print('La direccion de memoria de a es: ', f(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
La direccion de memoria de a es:  140697926822048
140697926822048
La direccion de memoria de a es:  None


In [100]:
#Diferentes objetos de matriz pueden compartir los mismos datos

c = a.view()

c is a

#C es una vista de los datos, verdadero
c.base is a

print('El valor de bandera de c es ', c.flags.owndata)
#Las dimensiones a no cambian
c = c.reshape((2, 6))
print('Las dimensiones de a son: ', a.shape)
#Cambia la data de a
c[0, 4] = 1234
print(a)
#Cortar una matriz devuelve una vista de la misma

s = a[:, 1:3]
# s es una vista de s. Es diferente a s = 10
s[:] = 10
print(a)

El valor de bandera de c es  False
Las dimensiones de a son:  (3, 4)
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
[[   0   10   10    3]
 [1234   10   10    7]
 [   8   10   10   11]]


In [102]:
#Copia profunda

#Se crea un nuevo objeto de matriz 
d = a.copy()
d is a


False

In [103]:
#d no comparte nada con a
d.base is a

False

In [104]:
d[0, 0] = 999

In [105]:
a


array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [ ]:
a = np.arange(int(1e8))
b = a[:100].copy()
#la memoria de a puede ser liberada
del a